name: Result Checker

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run result checker
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: node lib/checkResults.js
